### PR TITLE
show when notification will fire + some styles

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by patrickthumeyer — APPROVED** [review]
Looks great and works perfectly

**Review by eminaydin — COMMENTED** [review]
Looks great, only one improvement can be done though. It's not related to this pr but once you click on three dots you can still click on the set reminder button on the background. We might want to disable that.

**Comment by ghost** [comment]
> Looks great, only one improvement can be done though. It's not related to this pr but once you click on three dots you can still click on the set reminder button on the background. We might want to disable that.

Okay we might need to fix that next time.

**Review by Julianb18 — APPROVED** [review]
looks great and working smoothly

**Pull request merged**
