### PR TITLE
Motoki/push notification

### PR DESCRIPTION
**Pull request by motokikasai**
Here is what I have so far with Notification function. Go to 'MyGardenPlant' screen > click 'Set reminder' > choose the date & time, which should send out only one notification in 30 sec (*regardless of what you choose on Date Time picker!)

### CODE REVIEW

**Comment by eminaydin** [comment]
I am afraid the expected functionality doesn't work in IOS as I don't get any notifications so far.

**Comment by motokikasai** [comment]
Oh, no... I will have to look into it then. This is rather tricky to test and implement, I have to say! I had to reinstall Expo client on my Android phone several times since it gets stuck(cached??) often to the extent that I couldn't get it working without doing so...

**Comment by motokikasai** [comment]
I've added permission-related methods for iOS. My disclaimer: I have no way of testing this on my own without iPhone... In any case, check it out and see if you receive a notification this time on iPhone. Again, you should receive a notification in 30 sec, IF the issue has been solved!

**Comment by eminaydin** [comment]
> I've added permission-related methods for iOS. My disclaimer: I have no way of testing this on my own without iPhone... In any case, check it out and see if you receive a notification this time on iPhone. Again, you should receive a notification in 30 sec, IF the issue has been solved!

Seems like you don't even need to have an iphone to solve the problem. It is working like a charm :)

One tiny thing though, do you want to consider removing console logs and commented out lines?

**Review by Julianb18 — APPROVED** [review]
Looks really great!

**Comment by motokikasai** [comment]
Good to hear! I think most of the building blocks are there now. What we need is some 'logic' so everything will work as intuitively as possible. Let me know if there is any question, suggestion, etc...

**Review by ghost — CHANGES_REQUESTED** [review]
Hey Motoki . I just checked the branch . and got some errors as soon as I tried to open My Plant Screen. it looks like its related to Date somehow. I tried to follow the error and looks like notificationInputInMillisec variable has some issues . I tried to log it and it gives NaN and react native doesn't like this value. 

here is what I found https://github.com/facebook/react-native/issues/23835 and here is a comment related to moment js https://github.com/facebook/react-native/issues/23835#issuecomment-549196837

**Comment by motokikasai** [comment]
OK, I think the error is fixed (as far as I can tell!). It was a missing 'check' as to whether there is no date/time value -> set to ' ', which seems to have done the trick. But let me know if it actually did! 

Now, the parts that are (seemingly) working are the notification based on date&time input from user and basic functionalities of the modal view. My current plan is to find out how to implement the 'repeat function' and pack the data input from this modal view into an object and pass it to the notification component where the 'title field' will take the name of the flower, 'body field' will take the care options (*water, fertilize or repot), and add data for date, time and repeat.

**Comment by ghost** [comment]
Modal looks awesome by the way.  Yeah, we will figure out how to use this information for the notification.  And somehow the formatting also doesn't work somehow I know we fixed it after installing eslint not sure why it started to not format again.

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Oh and I believe before we merge you also need to merge master into your branch.

**Review by ghost — APPROVED** [review]

**Pull request merged**
