### PR TITLE
camera flash added and icon positioning

### PR DESCRIPTION
**Pull request by Julianb18**

### CODE REVIEW

**Review by eminaydin — CHANGES_REQUESTED** [review]
Seems like flash is working only on Android as it doesn't work for my iphone. I also believe that we need better style and concept for the camera icon. Maybe some text with a nice font.

**Comment by Julianb18** [comment]
Emin did you take a picture? when you put the flash on you have to take a picture and then it should work? I tested on ios and android I will have another look. Also I did not change the style of camera icon only the size I will change the style in another branch once we are set on a search screen background

**Comment by patrickthumeyer** [comment]
Works as expected for me but why does the plant recognition photo screen have only the flash toggle and the photo screen under myPlantPage the camera type toggle and the flash toggle? I would say maybe add the camera type toggle to the recognition screen too. It doesn´t make a lot of sense but for instance, my camera is broken and it´s good to have backup plus it looks more symmetrical. Happy to help you with that btw

**Comment by Julianb18** [comment]
yeah Ali and I decided on that because we didnt think there was a point to have it on plant recognition. We didnt know why someone would want to use the front camera for plant recognition. But it is an easy add if the rest agree it should be there

**Comment by eminaydin** [comment]
I am also on the same point with Patrick here. We can provide the option and let it to user to decide either to use it or not.

**Comment by patrickthumeyer** [comment]
Ok up to you. I also don´t see why it we would need it. I might be biased since the main camera on my phone is broken :D

**Comment by Julianb18** [comment]
It does look better though. I will add it now its an easy add

**Review by ghost — APPROVED** [review]
Great Job ! :+1:

**Review by eminaydin — APPROVED** [review]

**Pull request merged**
